name: dokan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  dartz: ^0.10.1
  http: ^1.2.1
  get_it: ^7.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  awesome_dialog: ^3.2.1
  awesome_snackbar_content: ^0.1.3
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.2
  get_storage: ^2.1.1
  animated_bottom_navigation_bar: ^1.3.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/bottom/